# This program says hello and asks for my name...
print("Hello there!")
print("Welcome to chipotle.")
print("Can I have your name for the order, please?")
myname= input()
print("Are there any drinks you'd like to order on our menu " + myname + "?")
drink= input()
print("what kind food would you like to get today?")
food= input()
print("Do you want the food for here or to go?")
desc= input()
print("Your total will be $15. What would you like to pay your order with?")
pay= input()
print("Is there anything that you feel should be on the menu list?")
ans= input()
print("Your order will be ready in 10 minutes. Thank you for stop by our restaurant. Have a good day " + myname + ".")